name: uni_quest_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.1
  flutter_localizations: # Correct package for localization
    sdk: flutter
  intl: ^0.19.0
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_lint: ^2.6.3
  riverpod_generator: ^2.6.3
  intl_utils: ^2.8.7
  mysql1: ^0.20.0
  dio: ^5.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true

  # Remove the l10n configuration here
  # You don't need to define the l10n configuration manually in pubspec.yaml for the new intl package
flutter_intl:
  enabled: true
  main_locale: en
